### ISSUE TITLE
Exceptions - add "throws" clause in the method headers

### ISSUE THREAD

**Issue by desrtfx** [lyudaio/jcards#10]
Methods that `throw` exceptions have to have their Exceptions declared in the *method header*, e.g. 

```
    public Card(Rank rank, Suit suit) throws IllegalStateException {
        if (rank == null) {
            throw new IllegalArgumentException("Rank cannot be null");
        }
        if (suit == null) {
            throw new IllegalArgumentException("Suit cannot be null");
        }
        this.rank = rank;
        this.suit = suit;
    }
```

This goes through the entire codebase in every single method that throws an exception.

**Comment by chabala** [comment]
@desrtfx `IllegalArgumentException` is a `RuntimeException`, not a checked exception, it does not need to declared in the signature, nor would that make any sense.

**Comment by lyudaio** [comment]
Closing this issue, will assess whether exceptions need to be adjusted.
