### ISSUE TITLE
Improvement suggestion - generic types

### ISSUE THREAD

**Issue by Remblej** [lyudaio/jcards#12]
Please validate the suggestion against your view on the project. Chances are you keep it simple and narrow-scoped for a reason.
But I noticed, that it would be not so complicated to change classes like Hand, Deck etc to support generic types, and change Card type to be an interface. Typical playing cards (hearths, spades etc) could still be provided as an implementation provided by a library. 
It would allow users to supply their own implementations  opening  up the project for other types of card games (like TCG games like Magic the Gathering).

**Comment by lyudaio** [comment]
In consideration for upcoming release.
