### ISSUE TITLE
Minimum supported Java version

### ISSUE THREAD

**Issue by MihajloNesic** [lyudaio/jcards#13]
Hello

It looks like the minimum Java version for this project is 19.
I suggest setting the minimum required version to 17, as it is the latest LTS version.

More about versions here https://en.wikipedia.org/wiki/Java_version_history

**Comment by lyudaio** [comment]
Will update the documentation on this for the next release and probably lower version to 17.

**Comment by Daniel-Gill** [comment]
Has this been completed? I would like to contribute, but I will only do so if the minimum version is set to 17.

**Comment by lyudaio** [comment]
Yes, POM has been updated to indicate JDK 17. Code was already compliant to latest LTS, I was just developing using 19.
